### ISSUE TITLE
Autocomplete suggestions styles | 

### ISSUE THREAD

**Issue by omdesignz** [LasseHaslev/vue-autocomplete#1]
How can I style this awesome plugin? I also cannot find a way to display the names from an array of objects.

**Comment by LasseHaslev** [comment]
Hi! To style this plugin, all you have to do is create an object that uses the "BaseAutocomplete" mixin. Please se how its done in the [Autocomplete class](https://github.com/LasseHaslev/vue-autocomplete/blob/master/src/components/Autocomplete.js).

I use this plugin mainly with http request as seen in the [README.md](https://github.com/LasseHaslev/vue-autocomplete). 

If you do however want to use this with just plain objects, the search function must return a [Promise.](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)

I have made 2 more examples that uses plain array and objects in [the tutorial folder].(https://github.com/LasseHaslev/vue-autocomplete/tree/master/src/tutorials).
